### ISSUE TITLE
Module '"./generated/schema"' has no exported member 'Query'.

### ISSUE THREAD

**Issue by lastmjs** [samdenty/gqless#103]
So I believe I successfully completed the generation, though perhaps not given this issue I'm having: https://github.com/samdenty/gqless/issues/102

In my `client.ts` file, I am getting a type error on one of the imports: 

```typescript
import { schema, Query } from './generated/schema';
```
I added in `schema` to the path, because that is generating an error as well. `schema` is defined just fine, but `Query` doesn't seem to be present, which of course ruins all types for me.

Any idea what could be going on here?

**Comment by samdenty** [comment]
Hmm, would seem you don't have a `Query` type. If you go to GraphiQL you should be able to find the custom name by looking at your schema
