### ISSUE TITLE
Possible optimization for React - JIT

### ISSUE THREAD

**Issue by jeffreyyoung** [samdenty/gqless#104]
I'm wondering about a possible optimization the React - JIT using proxies (STABLE) workflow that would remove the need for an additional render of the application in production.  I am looking for some discussion.

To do this feature the api would have to be updated to look like this `query("unique identifying string for this query").users.name`;  

The gist of the idea is in dev everything would work the same with the addition that whenever `gqless` finds a a full query, the query would be associated with a unique id and written to the filesystem. Anytime that query is updated during dev, the associated query snapshot would be updated as well

In practice the code would look like below
```javascript

const User = graphql(({ user }: { user: User }) => (
  <div>
    <h2>{user.name}</h2>
    <img src={user.avatarUrl({ size: 100 })} />
  </div>
))

const App = graphql(() => (
  <div>
    {query("load users").users.map(user => (
      <User key={user.id} user={user} />
    ))}
  </div>
))
```

When using `gqless` in production mode, if `query("load users")` is called, `gqless` would look for a query with the id "load users", if a query is found gqless would immediately send the query over the network, if the query is not found an error would be thrown.

To address some potential problems with this workflow:
* a linter could be added that would check for all instances of gqless("[query identifier]") and see if any queries have not been snapshotted.  This way a user will be able to know whether all of their queries have been snapshotted before running in prod mode.  This linter could be used to also evict not longer in use queries as well.

**Comment by samdenty** [comment]
The unnecessary render of your application can only be solved with compile-time tooling (which is what the second method will do - babel).

What you're suggestion sounds familiar for what I want to achieve with SSR. Essentially evaluating the app at build time / at CDN, with the same props as on client. Then extracting into queries - a lot of work eitherway

**Comment by jeffreyyoung** [comment]
right on!  I was just thinking creating the queries at compile time sounded really difficult and maybe this alternate method would be easier haha. Thanks for the awesome library!!!
