### ISSUE TITLE
Re-run query

### ISSUE THREAD

**Issue by natew** [samdenty/gqless#126]
Not sure if this exists, but a simple way to tell a query to re-run would be nice.

**Comment by natew** [comment]
It's exposed as `refetch`, for future reference: https://github.com/samdenty/gqless/blob/master/gqless/src/helpers/refetch.ts

**Comment by natew** [comment]
Just tested this and using refetch in an effect didn't update the view, but did re-run the query. If I add a forceUpdate afterwards it did show the new data, but you can't await the `refetch` as it doesn't return any promise.

**Comment by Yomanz** [comment]
You should be able to do `await resolved(refetch(xxx))`
