### ISSUE TITLE
Dev setup

### ISSUE THREAD

**Issue by taviroquai** [samdenty/gqless#129]
Hi,

How do I install @internal/fixtures ?

I get this error on running "npm run test":

> @0.0.0 test /mnt/c/Users/mafonso/Documents/projects/gqless
> jest
> Error: Cannot find module '@internal/fixtures'

Thanks!

**Comment by Yomanz** [comment]
You probably need to use yarn.

https://github.com/samdenty/gqless/tree/master/internal/fixtures
https://github.com/samdenty/gqless/blob/master/package.json#L5

**Comment by taviroquai** [comment]
Thanks I got it working. 

I tried to generate a new Jest snapshot to test a query with more than 3 levels deep but the way tests are created it is hard to test.

Example of test on file **/test/Client.test.ts**:

```js
it('fetches values 3 levels', async () => {
  const client = createGraphQL()

  client.query.object.grandchild.name
```

And this would be the schema (only relevant part):
```gql
type Grandchild {
  string: String!
}

type Object {
  string: String! @fake(type: firstName)
  string2: String! @fake(type: lastName)
  int: Int!
  enum: Enum!
  grandchild: Grandchild!

  overriddenString: String! @fake(type: firstName)
  overriddenInt: Int!
}
```

Can't find a way to do this.
