### ISSUE TITLE
Is it still being development or the project is dead?

### ISSUE THREAD

**Issue by lukejagodzinski** [samdenty/gqless#130]

**Comment by MaxmaxmaximusAWS** [comment]
@lukejagodzinski we can fork and continue development ourselves, I personally, for example, would add mutations and subscriptions in a day

**Comment by Yomanz** [comment]
> @lukejagodzinski we can fork and continue development ourselves, I personally, for example, would add mutations and subscriptions in a day

PR it and I can get review and merge it.

The project isn't dead but the main maintainer is currently busy with other work.

**Comment by MaxmaxmaximusAWS** [comment]
@Yomanz ahah yes, here I am too working (I literally have nothing to eat, I have to make an order ahah) but this library is exactly what I have been thinking about for many years while writing on graphql, so I am thinking of writing a MANUAL graphql query is the last century. And reactive libraries like these that queried only for what we really need are the future.

**Comment by lukejagodzinski** [comment]
I think author tried to do too much for the v1 release. It would be just good enough if it has support for mutations and main bugs are fixed without any fancy features that were planned. Will just wait. Would love to use this library.

**Comment by MaxmaxmaximusAWS** [comment]
In mutations, the difficulty is that, unlike query, we cannot do a second mutation when the system requests new fields. For example:

```js
function Chat() {
  const message = mutation.sendMessage()

  if(!message.author) {
    return null
  }

  return <div>
    {message.text}
  </div>
}
```

, in this case, at the stage of scanning the structure of the requested data, we will see that only the author property is requested. This is a scalar, and during the scan phase, it will return null. So the code execution won't reach the `message.text` line and the text field won't be requested. In the case of query, we could, when re-rendering, request the text property. But in the case of a mutation, we cannot re-send the mutation to the server, since this will cause a second message to be sent, because mutations are imperative, not declarative.

**Comment by Yomanz** [comment]
> 
> 
> In mutations, the difficulty is that, unlike query, we cannot do a second mutation when the system requests new fields. For example:
> 
> ```js
> function Chat() {
>   const [sendMessage, message] = mutation.sendMessage()
> 
>   if(!message.author) {
>     return null
>   }
> 
>   return <div>
>     {message.text}
>   </div>
> }
> ```
> 
> , in this case, at the stage of scanning the structure of the requested data, we will see that only the author property is requested. This is a scalar, and during the scan phase, it will return null. So the code execution won't reach the `message.text` line and the text field won't be requested. In the case of query, we could, when re-rendering, request the text property. But in the case of a mutation, we cannot re-send the mutation to the server, since this will cause a second message to be sent, because mutations are imperative, not declarative.
> 
> On this we have two ways, or resort to inexact static analysis through babel. Or force the programmer to give hints about the requested fields, which calls into question the whole idea of the gqless library.
> 
> But I came up with a solution ;) 👍
> 
> I generally think that the runtime version of gqless is doomed to fail, since it contradicts the whole idea of graphql (get all the data in one request). in any case, we DECLARE the data that we want to receive. the problem is that we declare it twice. once in the code, the second time in the gql tag

Yeah, that makes total sense **but**, I doubt that the static analysis feature would be done any time soon.
Feel free to do it yourself obviously and I would get the owner to review the PR but I don't think he will be coding it anytime soon. 
I might take a look myself but I probably wouldn't get very far :)

**Comment by samdenty** [comment]
I've posted an update over here - https://github.com/gqless/gqless/discussions/142#discussioncomment-351713
