### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by PascalSenn** [samdenty/gqless#20]
Great Library! 
Really love it! 

As you are using Proxies. How is Internet Explorer supported?

**Comment by capaj** [comment]
If it's using proxies you can forget about Internet explorer. Even 11 does not have them.

**Comment by PascalSenn** [comment]
There are pollyfills, but they are slow as hell and provide only a partial support.. 
So i wonder what needs to be supported

**Comment by capaj** [comment]
With the code generation maybe it's only needed for generating the queries? Maybe in runtime you don't need proxy support? That would be nice.

**Comment by PascalSenn** [comment]
Indeed. But it's not a Babel plugin or anything. It's really all doing at runtime. And this probably is the big difference from other libraries
>No need to write queries - auto-generated at runtime

**Comment by samdenty** [comment]
Although I could switch to getters, it would be slower + would place architectural limitations.

gqless is similar to mobx, which also doesn't support IE
