### ISSUE TITLE
CLI cant generate

### ISSUE THREAD

**Issue by Yomanz** [samdenty/gqless#23]
![image](https://user-images.githubusercontent.com/5119107/67976277-b13f4980-fc0d-11e9-923f-2a333a170275.png)

When running `gqless generate`, it shows that the command `generate` cant be found.
I've tested on another computer as well.

Following https://gqless.netlify.com/docs/getting-started/

**Comment by victionn** [comment]
Another issue with this - it complains that the "globby" module is not installed, you can fix it by just installing globby yourself but you shouldn't have to do that...
