### ISSUE TITLE
useRefetch not working properly

### ISSUE THREAD

**Issue by AdamSchinzel** [samdenty/gqless#242]
Hi!

It seems that useRefetch is not working properly in our Next.js app, because it only works once.

We have list of users and you can add new or delete them with modal.

Our function looks like this:

```jsx
const handleRefetch = () =>
  refetch(() => query.accounts.map((it) => [it.id, it.email, it.first_name, it.last_name, it.role]));
```

and then we call it inside modal function like this

```jsx
const handleDelete = () => {
    if (deleteModalTarget === undefined) return;
    mutate((mutation) => mutation.deleteUser({ userId: deleteModalTarget })).then(() => {
      handleRefetch();
    });
    setShowDeleteModal(false);
  };
```

So if you for example delete one user with modal, it's gone but if you try to delete second, you still see him because it didn't refetch query.accounts and you must reload the page.

Do you want a reproduction or do you see the problem just from this code?

Thanks for help

**Comment by vicary** [comment]
@AdamSchinzel Haven't got time to triage old issues yet, does the latest alpha fix it?

**Comment by AdamSchinzel** [comment]
No problem. I migrated to other solution.
