### ISSUE TITLE
Don't warn `✘ [ERROR] [gqty] Warning! No data requested.` if `onEmptyResolve` is provided for a query

### ISSUE THREAD

**Issue by bkniffler** [samdenty/gqless#245]
I think we could avoid having the warning if an `onEmptyResolve` is explicitly provided in development mode. What do you think?

**Comment by vicary** [comment]
@bkniffler The error message hints another project, we may discuss this in the correct repo.

**Comment by bkniffler** [comment]
Ah, sorry, will open in gqty!

**Comment by bkniffler** [comment]
https://github.com/gqty-dev/gqty/issues/1614
