### ISSUE TITLE
Generate giving 400 with working API.

### ISSUE THREAD

**Issue by Yomanz** [samdenty/gqless#30]
We're trying to use this with our [GraphQL API](https://docs.nestjs.com/graphql/quick-start).
![image](https://user-images.githubusercontent.com/5119107/68074751-9d731f00-fd96-11e9-98ff-dc43da3003fe.png)
```json
"gqless": {
    "url": "https://****.*****.***/api/graphql",
    "outputDir": "src/graphql"
}
```

If you want access to the API just message me.

**Comment by victionn** [comment]
To add on to this, when you add
`"usePost": true` onto the config, then it generates some code however there are errors with it and also errors in the console...

![image](https://user-images.githubusercontent.com/26467584/68074931-12475880-fd99-11e9-8d88-540843d23055.png)

![image](https://user-images.githubusercontent.com/26467584/68074938-2e4afa00-fd99-11e9-9a93-30d277694a9f.png)

**Comment by samdenty** [comment]
@victionn can you post a gist of the outputted folder

**Comment by samdenty** [comment]
Believe this was caused by an unimplemented interface
