### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by mu29** [samdenty/gqless#38]
I really like the concept of this library and want to use it in production apps,
but it does not seem to support the pagination function.
The only clue is `fetchMore` in the [NEW_API_EXAMPLES](https://github.com/samdenty/gqless/blob/master/SPEC/NEW_API_EXAMPLES.md) document, which does not seem to be implemented.

**Comment by samdenty** [comment]
It's planned, but not a priority at the moment.
I'm currently working on static analysis

**Comment by PabloSzx** [comment]
I recently added pagination support to [gqless-hooks](https://github.com/PabloSzx/gqless-hooks#pagination) with a fetchMore function if anyone wants to check it out.
