### ISSUE TITLE
Multiple endpoint workflow

### ISSUE THREAD

**Issue by joltmode** [samdenty/gqless#45]
Lots of GraphQL React clients do not provide a first-class way of using multiple GraphQL endpoints.

There are even opinions that it's against the GraphQL way and one should always aim towards a singular endpoint either by using stitching or gateways or whatnot.

But, there are usually problems with these approaches.  
For instance, Apollo first came on board with schema-stitching, now having dropped it in favor of Federation. Cool! But not cool when one is looking to combine a 3rd party GraphQL endpoint with a managed one, where the 3rd party may not be Federation compliant.

I will be honest - I haven't done the homework of using this library yet and checking if that's already possible, though, skimming through the docs, I see no mention of it. Also, viewing the React examples, it hints to me, that it's impossible at this time.

I see how it could be used outside React, that's also the case for all the other clients - outside React, everything _is gucci_. Though, in React, because of the client usually being provided via a singular Provider, that's causing headaches. 

Not to mention the plethora of problems when one is looking to integrate TypeScript and type-checking for multiple endpoints.

So, is it currently possible to work with multiple clients? If not, how about adopting such usage as first-class for this library?

**Comment by samdenty** [comment]
Yep totally. gqless is designed to flexible in that way.

You can import multiple clients, with different endpoints - and use them together. Should just work

Publishing the client as an NPM package is also something you could do, `import { query } from '@github/graphql'`

**Comment by joltmode** [comment]
Damn, I guess I better get on with hands-on testing!

And this works because graphql HoC just sets up some interceptors and then checks the underlying accessors?

I mean, this should be fine:
```
import { graphql } from '@gqless/react'
import { query as shopify } from '@shopify/gqless'
import { query as sanity } from '@sanity/gqless'

const Component = graphql(() => <div>{shopify.hello} + {sanity.world}</div>)
```

**Comment by samdenty** [comment]
@joltmode Yep essentially!
All the types and whatnot are auto-inferred that way, unlike with using `ApolloClient.Provider`

**Comment by samdenty** [comment]
Currently to publish stuff to NPM, you have to do it manually - but I intend to create tooling around that.

Will auto create a README, run the generator + publish with semver inferred from schema changes

**Comment by joltmode** [comment]
I like your confidence!

Cool! Can't wait to start tinkering with this!

**Comment by bugproof** [comment]
It would be nice if gqless.config.js supported multiple endpoints so you could just do `gqless generate` and it would generate multiple clients in different directories.
