### ISSUE TITLE
Local schema

### ISSUE THREAD

**Issue by denkristoffer** [samdenty/gqless#49]
👋 

I think it'd be worthwhile to be able to point the config file to a local schema file instead of a remote endpoint, essentially using gqless to manage local state, in a way. This way you can decide later to sync with a remote GraphQL endpoint. What do you think of such an idea?

**Comment by samdenty** [comment]
For local state management you can use Extensions. You can pretty much use any library - MobX, xstate, redux, rxjs and everything should work.

For example:

```js
export const Query = {
  plainObject: {
    add: true
  },
  observable: mobx.observable.object({})
}
```

I'm not so sure on what having the local schema would accomplish. Can you elaborate?

I guess possibly for the Cache / Interfaces / Field arguments, but I feel like extensions are way better

**Comment by denkristoffer** [comment]
I should've explained my use case in the initial post, sorry 🙂 It's not that I particularly want a local schema, but I've been looking for a GraphQL client for that's client/local first but can, optionally, be synced to a remote endpoint later, say for React Native apps. I believe the vision of GraphQL permeating both local and remote state will become a more widespread reality, so in my mind it makes sense that a client doesn't need a remote endpoint to work.

> You can point it to an invalid endpoint URL, and it won't make any requests if you only interact with the extensions

That doesn't seem to work for me, probably if there's no `200` response from the given endpoint?

**Comment by lukejagodzinski** [comment]
@denkristoffer I guess for that you don't need local schema. The similar use case is application that lost connection to the server. How to use application as it's connected to the server? You just perform optimistic updates locally and store all the queries that you performed. When connection goes back online you just commit all the queries to the server. I can't imagine synchronizing entire local schema on demand. For that you would need extra mutation that should be able to update huge chunks of DB which is rather not good idea. Any synchronization should happen on per query level.

**Comment by samdenty** [comment]
Using extensions you can pretty much mock out anything, using plain JS. Albeit you don't have stuff like interfaces - but you can implement that pattern ontop gqless.

See [this for usage](https://twitter.com/thesamdd/status/1240792717652897796) & and [codesandbox demo](https://codesandbox.io/s/strange-booth-05uvr?fontsize=14&hidenavigation=1&initialpath=%2Fmovie%2F2e7f4c98-1311-4064-bffb-c914dc2edc7e&module=%2Fsrc%2Fmovies_api%2Fextensions%2FMovie.ts&theme=dark)

**Comment by adrianhunter** [comment]
@samdenty do extension currently only work with react?
