### ISSUE TITLE
Polling without throwing promise

### ISSUE THREAD

**Issue by lukejagodzinski** [samdenty/gqless#54]
Hey, I've modified hackernews example to use polling every 5 seconds https://codesandbox.io/s/gqless-polling-y8k50

The effect is that the `Loading...` indicator is being displayed every 5 seconds while it's reloading data from the server. Is it possible to just serve data from the cache while it's loading and then just update it data and rerender component? I guess it would require not throwing promise fetching data and just invalidating components that require this data after updating cache.

**Comment by samdenty** [comment]
Fixed in @gqless/react@0.0.1-alpha.28 https://codesandbox.io/s/gqless-polling-jbobc

**Comment by lukejagodzinski** [comment]
That was fast! Thank you! :)
