### ISSUE TITLE
Suggestion about @gqless scope

### ISSUE THREAD

**Issue by lukejagodzinski** [samdenty/gqless#56]
I've seen in the GH projects that you're considering changing package name. Whatever decision you're gonna make I would just like to propose renaming `gqless` package to `@gqless/core` or similar. It's a good pattern to have everything under one namespace/scope so it's easier for example to upgrade all packages in batch. Similar naming is used by many packages, one example could be `@material-ui/core`, `@material-ui/styles` etc. So just a suggestion :)

**Comment by samdenty** [comment]
I guess I could do something like `@gqless/client`.

apollo client moved to a all-in-one approach `https://unpkg.com/browse/@apollo/client@3.0.0-beta.41/react/`, I'm debating whether to adopt that too - for `@gqless/react` at least.

I'm going to be making `@gqless/cli` auto-installed when you install `gqless` though, so `@gqless/{core,client}` may be confusing

I'm not sure tbh

**Comment by lukejagodzinski** [comment]
Oh I see. I didn't know that they made this move. So it would end up being `@gqless/client/react`?
From what I see they are reexporting everything from the react package so without tree-shaking it could be a problem, I guess? (if understand that properly). But probably that's not a big deal as most of the bundlers have tree-shaking support.

IMHO `@gqless/client` + `@gqless/cli` is not confusing.

From what I see apollo will still have `apollo` package as the cli tool. Hmm as I understand that they want to have the same package name as the cli command name. I would rather come with what you did for cli `@apollo/cli`.

I think, having everything scoped + one package without scope makes things really confusing :)

But it's up to you :)

**Comment by elderapo** [comment]
I think it's a good practice to split CLI and client code into 2 packages.

`@gqless/cli` would go to `devDependencies` and `@gqless/client` to `dependencies`. This way `yarn/npm install --production` won't pollute production `node_modules` with development libraries.

**Comment by samdenty** [comment]
Yeah I agree, will keep them separated for now. Going to keep the `gqless` package name for now though as it's shorter
