### ISSUE TITLE
Mention prettier usage on code generation

### ISSUE THREAD

**Issue by lukejagodzinski** [samdenty/gqless#57]
I was about to ask for the prettier support on code generation as it's done for example in the `graphql-codegen` but I see that it's already implemented out of the box here: https://github.com/samdenty/gqless/blob/c7574aebc39846a640222b22aaab5cf588f5bbf9/packages/cli/src/utils/generateSchema.ts#L26

I can update docs if you want, just tell me where such information should land.

**Comment by samdenty** [comment]
I guess documented inside the CLI. https://github.com/samdenty/gqless/blob/master/packages/cli/src/commands/generate.ts

Should probably import the MD file from https://github.com/samdenty/gqless/tree/master/packages/cli#gqless-generate-output_dir into the docusaurus site

**Comment by lukejagodzinski** [comment]
Hmmm a new sections in docs would be definitely a good idea.

I can work on that tomorrow :)

**Comment by lukejagodzinski** [comment]
Updated docs for now. Don't know where exactly add info about prettier to the CLI code itself. It doesn't seem like a good place to add such info. Probably docs is sufficient.
