### ISSUE TITLE
question re: `Arrays will have a length of 1`

### ISSUE THREAD

**Issue by smeijer** [samdenty/gqless#75]
As the `readme` writes:

> All the GraphQL objects will be available, but the data on them won't.
> 
> Arrays will have a length of 1
> Scalars will return null

Is there a reason why arrays become `[null]` and not just `[]`? It's definitly not a deal-breaker, but `[]` would be a bit more convenient for the developer.

**Comment by elderapo** [comment]
It's not `[null]` but `[proxy]`. The reason why it has to be like that is your component needs to render so `gqless` can detect what data component is relying on to create appropriate graphql query.

**Comment by smeijer** [comment]
Thanks, that makes sense indeed. I understand that it wouldn't be possible to detect the nested fields without it.

I guess devtools had me fooled:

![gqless](https://user-images.githubusercontent.com/1196524/77940356-e503c580-72b8-11ea-8794-1f24da5ee743.gif)
