### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by rhlsthrm** [samdenty/gqless#78]
Trying to run a simple query in a node.js project, getting this error:

```
[ <1 empty item> ]
ReferenceError: fetch is not defined
```

Does this package not work outside the browser?

Edit: I got it to work by manually adding the `node-fetch` package to the generated `client.ts` code.

**Comment by samdenty** [comment]
Should probably mention this in the docs, but yeah you need to update the client's fetchQuery
