### ISSUE TITLE
Fields are wrongly typed as `null | undefined`

### ISSUE THREAD

**Issue by Arrow7000** [samdenty/gqless#91]
I initially thought it was just my own GraphQL API that was misconfigured but this even happens with publicly available endpoints.

I've run `gqless generate` with the endpoint set to `https://graphql-pokemon.now.sh` and it does generate a bunch of types. But each property of the `query` object seems to have type `null | undefined`. 

This seems to be the full type of `query`:

```
(alias) const query: {
    __typename: "Query";
    query?: {
        __typename: "Query";
        query?: {
            __typename: "Query";
            query?: {
                __typename: "Query";
                query?: {
                    __typename: "Query";
                    query?: {
                        __typename: "Query";
                        query?: {
                            __typename: "Query";
                            query?: {
                                ...;
                            } | ... 1 more ... | undefined;
                            pokemons?: null | undefined;
                            pokemon?: null | undefined;
                        } | null | undefined;
                        pokemons?: null | undefined;
                        pokemon?: null | undefined;
                    } | null | undefined;
                    pokemons?: null | undefined;
                    pokemon?: null | undefined;
                } | null | undefined;
                pokemons?: null | undefined;
                pokemon?: null | undefined;
            } | null | undefined;
            pokemons?: null | undefined;
            pokemon?: null | undefined;
        } | null | undefined;
        pokemons?: null | undefined;
        pokemon?: null | undefined;
    } | null | undefined;
    pokemons?: null | undefined;
    pokemon?: null | undefined;
}
```

So when I try to access either the `pokemon` or `pokemons` field they are both typed as `pokemons?: null | undefined`. I also get a TS error saying `Type instantiation is excessively deep and possibly infinite.ts(2589)` which may be what is ultimately causing this in the first place.

Either way the TypeScript information for a publicly available API isn't working because gqless gives up trying to type any of the possible queries.

**Comment by Yomanz** [comment]
There is a PR to fix this error

**Comment by Arrow7000** [comment]
Ah great. Which one? I couldn't see any issues about this.

**Comment by Arrow7000** [comment]
Ah yes I can see it: https://github.com/samdenty/gqless/pull/90

Thanks for working on it!

Looks like it's still failing some tests though

**Comment by Yomanz** [comment]
> 
> 
> Ah yes I can see it: #90
> 
> Thanks for working on it!
> 
> Looks like it's still failing some tests though

Those tests are currently broken.

**Comment by Suniron** [comment]
Hi, i have the same problem.

How can i fix it for now ?

Thanks :)

**Comment by PabloSzx** [comment]
![nullable blug](https://user-images.githubusercontent.com/8672915/80296376-82cba280-8748-11ea-980f-2a5397065f4a.png)
![fix nullable blug](https://user-images.githubusercontent.com/8672915/80296377-84956600-8748-11ea-9225-cf49e71a1791.png)

@Suniron the fix for now that the PR is not merged nor released in just changing the `?` in the generated type, like the images show
