### ISSUE TITLE
Query batching

### ISSUE THREAD

**Issue by sfcgeorge** [samdenty/gqless#92]
It would be nice if like Apollo you could optionally choose to have queries batched together. AKA if 5 components request data, the client would make just 1 request with an array of queries. This is good for reducing network requests and tends to speed up apps provided the queries are fast. 

It should still be optional as with slow queries it may make overall load time slower. E.g. we have one place in our app where we disable batching because a few of the queries are very slow so it's better to have them run in parallel such that the faster queries finish and render without waiting for the slow ones.

**Comment by samdenty** [comment]
We do this already, albeit in a different way.

With apollo it's combines queries into one requests.

```ts
["query A {a}", "query B {b}"]
```

gqless combines everything into one query:

```graphql
query App {
  a
  b
}
```

**Comment by sfcgeorge** [comment]
I saw that (which is very neat), but that's only within a single file correct? We'll often have a single Apollo client at the top level of our app, then multiple different components in separate files all making queries, and they're still batched.

I'm assuming that each `import { query } from './gqless'` creates its own "context" and only batches within that. Or does it globally batch already?

**Comment by samdenty** [comment]
@sfcgeorge Batches globally across the client

**Comment by sfcgeorge** [comment]
Awesome! Batching by default and manually splitting when desirable seems like a way better default. Thank you 😁

**Comment by lukejagodzinski** [comment]
Just to add to that it would be good batching time to be configurable. I've seen in the code that it uses 50 ms setTimeout. Probably in most cases that's good enough but probably someone would like to configure it.

**Comment by samdenty** [comment]
@lukejagodzinski should be able to do:

client.scheduler.interval = 100

**Comment by lukejagodzinski** [comment]
@samdenty good point, in deed it should work
